CREATE TABLE tract_relationship_2010(
STATE00 character varying(2),
COUNTY00 character varying(3),
TRACT00 character varying(6),
GEOID00 character varying(11),
POP00 integer,
HU00 integer,
PART00 character varying(1),
AREA00 double precision,
AREALAND00 double precision,
STATE10 character varying(2),
COUNTY10 character varying(3),
TRACT10 character varying(6),
GEOID10 character varying(11),
POP10 integer,
HU10 integer,
PART10 character varying(1),
AREA10 double precision,
AREALAND10 double precision,
AREAPT double precision,
AREALANDPT double precision,
AREAPCT00PT double precision,
AREALANDPCT00PT double precision,
AREAPCT10PT double precision,
AREALANDPCT10PT double precision,
POP10PT integer,
POPPCT00 double precision,
POPPCT10 double precision,
HU10PT integer,
HUPCT00 double precision,
HUPCT10 double precision)
